In [147]:
import numpy 
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
numpy.random.seed(10)

In [148]:
all_df = pd.read_csv("data/bank.csv")

In [149]:
cols=['age','balance' ,'day', 'duration',
       'campaign','pdays','previous','deposit']
all_df=all_df[cols]

In [150]:
all_df['deposit']= all_df['deposit'].map({'no':0, 'yes': 1}).astype(int)

In [151]:
X=all_df.drop(['deposit'], axis=1).values.astype('float64')

In [152]:
Y = all_df['deposit'].values.astype('int64')

In [153]:
X = StandardScaler().fit_transform(X)
train_Features, test_Features, train_Label, test_Label = train_test_split(X, Y, test_size=0.2, random_state=True) 
len(train_Features)

8929

In [154]:
test_Features[:2]

array([[-0.85890111, -0.3021573 , -1.26574556, -0.8008745 , -0.55416834,
        -0.48118405, -0.36325984],
       [ 0.14841574, -0.31455937,  0.51565047, -0.97372895, -0.18678537,
        -0.48118405, -0.36325984]])

In [155]:
train_Label[:4]

array([0, 1, 0, 1])

In [156]:
train_Features.shape

(8929, 7)

In [157]:
test_Label[:4]

array([0, 0, 0, 1])

In [158]:
train_Features = train_Features.reshape((train_Features.shape[0], train_Features.shape[1], 1))

In [159]:
test_Features = test_Features.reshape((test_Features.shape[0], test_Features.shape[1], 1))

In [160]:
train_Label = train_Label.reshape(train_Label.shape[0], 1)
test_Label= test_Label.reshape(test_Label.shape[0], 1)

In [161]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Conv1D,MaxPooling1D
from keras.layers.embeddings import Embedding
from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=2)

In [162]:
model = Sequential()

In [163]:
model.add(Conv1D(filters=7*5,
                 kernel_size=3,
                 padding='valid',
                 input_shape=(7,1), 
                 activation='relu'))

In [164]:
model.add(MaxPooling1D(pool_size=1))

In [165]:
model.add(Conv1D(filters=7*4,
                 kernel_size=3,
                 padding='valid',
                 activation='relu'))

In [166]:
model.add(MaxPooling1D(pool_size=1))

In [167]:
model.add(Conv1D(filters=7*3,
                 kernel_size=3,
                 padding='valid', 
                 activation='relu'))

In [168]:
model.add(MaxPooling1D(pool_size=1))

In [ ]:
model.add(Flatten())

In [ ]:
model.add(Dense(7, activation='tanh'))

In [ ]:
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.summary()

In [ ]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

In [ ]:
train_history =model.fit(x=train_Features, 
                         y=train_Label, 
                         validation_split=0.2, 
                         epochs=60, 
                         batch_size=500,verbose=1,callbacks=[early_stopping])

In [ ]:
import matplotlib.pyplot as plt
def show_train_history(train_history,train,validation):
    plt.plot(train_history.history[train])
    plt.plot(train_history.history[validation])
    plt.title('Train History')
    plt.ylabel(train)
    plt.xlabel('Epoch')
    plt.legend(['train', 'validation'], loc='upper left')
    plt.show()

In [ ]:
show_train_history(train_history,'acc','val_acc')

In [ ]:
show_train_history(train_history,'loss','val_loss')

In [ ]:
scores = model.evaluate(x=test_Features, 
                        y=test_Label)

In [ ]:
scores[1]