In [351]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
np.random.seed(10)

In [352]:
filepath="data/pima-indians-diabetes.xls"
all_df=pd.read_excel(filepath)

In [353]:
cols=['Outcome','Pregnancies','Glucose','Blood','Skin','Insulin',
      'BMI','Diabetes', 'Age']
all_df=all_df[cols]

In [354]:
all_df[:5]

Outcome  Pregnancies  Glucose  Blood  Skin  Insulin   BMI  Diabetes  Age
0        1            6      148     72    35        0  33.6     0.627   50
1        0            1       85     66    29        0  26.6     0.351   31
2        1            8      183     64     0        0  23.3     0.672   32
3        0            1       89     66    23       94  28.1     0.167   21
4        1            0      137     40    35      168  43.1     2.288   33

In [355]:
msk = np.random.rand(len(all_df)) < 0.8
train_df = all_df[msk]
test_df = all_df[~msk]

In [356]:
print('total:',len(all_df),
      'train:',len(train_df),
      'test:',len(test_df))

total: 768 train: 616 test: 152


In [357]:
    ndarray = train_df.values
    ndarray2=test_df.values
    train_Features=ndarray[:,1:]
    train_Label=ndarray[:,0]
    test_Features=ndarray2[:,1:]
    test_Label=ndarray2[:,0]

In [358]:
train_Features[:2]

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ],
       [  1.   ,  85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351,
         31.   ]])

In [359]:
train_Label[:2]

array([1., 0.])

In [360]:
test_Features[:2]

array([[ 10.   , 168.   ,  74.   ,   0.   ,   0.   ,  38.   ,   0.537,
         34.   ],
       [  5.   , 166.   ,  72.   ,  19.   , 175.   ,  25.8  ,   0.587,
         51.   ]])

In [361]:
test_Label[:2]

array([1., 1.])

In [362]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import SimpleRNN

In [363]:
model = Sequential()

In [364]:
model.add(Embedding(input_dim=8,output_dim=1))

In [365]:
model.add(SimpleRNN(units=5))

In [366]:
model.add(Dense(1, activation = "sigmoid"))

In [367]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_12 (Embedding)     (None, None, 1)           8         
_________________________________________________________________
simple_rnn_16 (SimpleRNN)    (None, 5)                 35        
_________________________________________________________________
dense_16 (Dense)             (None, 1)                 6         
Total params: 49
Trainable params: 49
Non-trainable params: 0
_________________________________________________________________


In [368]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

In [369]:
train_history =model.fit(x=train_Features, 
                         y=train_Label, 
                         validation_split=0.1, 
                         epochs=30, 
                         batch_size=30,verbose=2)

Train on 554 samples, validate on 62 samples
Epoch 1/30


InvalidArgumentError: indices[0,0] = 13 is not in [0, 8)
	 [[Node: embedding_12/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@training_11/Adam/Assign_2"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_12/embeddings/read, embedding_12/Cast, training_11/Adam/gradients/embedding_12/embedding_lookup_grad/concat/axis)]]

In [ ]:
import matplotlib.pyplot as plt
def show_train_history(train_history,train,validation):
    plt.plot(train_history.history[train])
    plt.plot(train_history.history[validation])
    plt.title('Train History')
    plt.ylabel(train)
    plt.xlabel('Epoch')
    plt.legend(['train', 'validation'], loc='upper left')
    plt.show()

In [ ]:
show_train_history(train_history,'acc','val_acc')

In [ ]:
show_train_history(train_history,'loss','val_loss')

In [ ]:
scores = model.evaluate(x=test_Features, 
                        y=test_Label)

In [ ]:
scores[1]