In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
np.random.seed(10)

In [2]:
filepath="data/pima-indians-diabetes.xls"
all_df=pd.read_excel(filepath)

In [3]:
cols=['Outcome','Pregnancies','Glucose','Blood','Skin','Insulin',
      'BMI','Diabetes', 'Age']
all_df=all_df[cols]

In [4]:
all_df[:5]

Outcome  Pregnancies  Glucose  Blood  Skin  Insulin   BMI  Diabetes  Age
0        1            6      148     72    35        0  33.6     0.627   50
1        0            1       85     66    29        0  26.6     0.351   31
2        1            8      183     64     0        0  23.3     0.672   32
3        0            1       89     66    23       94  28.1     0.167   21
4        1            0      137     40    35      168  43.1     2.288   33

In [5]:
zero_not_accepted = ['Glucose', 'Blood', 'Skin', 'BMI', 'Insulin']       
for column in zero_not_accepted: 
    mean = int(all_df[column].mean(skipna=True))
    all_df[column].replace(0, mean,inplace=True) 

In [6]:
msk = np.random.rand(len(all_df)) < 0.8
train_df = all_df[msk]
test_df = all_df[~msk]
print('total:',len(all_df),
      'train:',len(train_df),
      'test:',len(test_df))  

total: 768 train: 616 test: 152


In [7]:
trainray= train_df.values
train_Features = trainray[:,1:]
train_Label = trainray[:,0]
    
testray= test_df.values
test_Features = testray[:,1:]
test_Label = testray[:,0]

    
train_Features=StandardScaler().fit_transform(train_Features)
test_Features=StandardScaler().fit_transform(test_Features)

In [8]:
train_Features[:2]

array([[ 0.68004207,  0.88222526, -0.02133549,  0.86471493, -0.41811974,
         0.17467821,  0.45102803,  1.46416999],
       [-0.82248991, -1.18724996, -0.5141854 ,  0.24389395, -0.41811974,
        -0.83134882, -0.36630283, -0.17444596]])

In [9]:
train_Label[:2]

array([1., 0.])

In [10]:
test_Features[:2]

array([[ 1.63837785,  1.4616998 ,  0.1510988 , -0.56924141, -0.43622157,
         0.82197801,  0.25283098, -0.01013739],
       [ 0.20550424,  1.39550634, -0.01777633, -0.66985152,  0.64246766,
        -1.0515176 ,  0.41798057,  1.36854704]])

In [11]:
test_Label[:2]

array([1., 1.])

In [12]:
import numpy as np
import pandas as pd
from sklearn import  ensemble, metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn import svm

In [13]:
tree=DecisionTreeClassifier(criterion='gini',max_depth=5) 
tree_clf=tree.fit(train_Features,train_Label)

In [14]:
y_test_predicted = tree_clf.predict(test_Features)

In [15]:
testAccuracy = metrics.accuracy_score(test_Label, y_test_predicted)
print('準確率:',testAccuracy)

準確率: 0.7368421052631579
