In [60]:
import numpy
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
numpy.random.seed(10)

In [61]:
all_df = pd.read_csv("data/abalone.csv")

In [62]:
all_df['Sex']= all_df['Sex'].map({'M':0,'F': 1,'I': 2}).astype(int) 

In [63]:
all_df[:4]

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0    0   0.455     0.365   0.095        0.5140          0.2245   
1    0   0.350     0.265   0.090        0.2255          0.0995   
2    1   0.530     0.420   0.135        0.6770          0.2565   
3    0   0.440     0.365   0.125        0.5160          0.2155   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10

In [64]:
all_df.shape

(4177, 9)

In [65]:
X=all_df.drop(['Rings'], axis=1).values

In [66]:
Y = all_df['Rings'].values.astype('int64')

In [67]:
Y[:5]

array([15,  7,  9, 10,  7])

In [68]:
 X = StandardScaler().fit_transform(X)
train_Features, test_Features, train_Label, test_Label = train_test_split(X, Y, test_size=0.2, random_state=True) 
len(train_Features)

3341

In [69]:
train_Features[355:359]

array([[-1.15434629,  1.04937905,  1.12991052,  1.68532154,  1.73303142,
         1.38387638,  1.16245511,  1.58901852],
       [-1.15434629, -1.19914936, -1.23837296, -0.94486999, -1.14666   ,
        -1.10107001, -1.09117132, -1.17706417],
       [ 1.26194258, -0.24144281, -0.33137077,  0.01156329, -0.68268706,
        -0.80368748, -0.75814555, -0.34364704],
       [ 0.05379815,  0.00839368,  0.12213032,  0.48977993, -0.14835338,
        -0.38239557, -0.06928403,  0.2598619 ]])

In [70]:
train_Label[:4]

array([11,  4,  8, 11])

In [71]:
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=2)

In [72]:
model = Sequential()

In [73]:
model.add(Dense(units=8*2,   input_dim=8,
                kernel_initializer='uniform', 
                activation='relu'))

In [74]:
model.add(Dense(units=8,   
                kernel_initializer='uniform', 
                activation='relu'))

In [75]:
model.add(Dense(units=1, 
                kernel_initializer='uniform',
                activation='sigmoid'))

In [76]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 16)                144       
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 9         
Total params: 289
Trainable params: 289
Non-trainable params: 0
_________________________________________________________________


In [77]:
model.compile(loss='categorical_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

In [78]:
train_history =model.fit(x=train_Features, 
                         y=train_Label, 
                         validation_split=0.1, 
                         epochs=60, 
                         batch_size=60,verbose=1,callbacks=[early_stopping])

Train on 3006 samples, validate on 335 samples
Epoch 1/60


InvalidArgumentError: Received a label value of 16 which is outside the valid range of [0, 1).  Label values: 8 12 4 12 12 9 11 8 10 11 7 7 12 14 9 10 11 7 8 10 11 13 16 11 15 10 11 10 13 10 6 12 9 9 4 14 10 10 14 8 13 9 8 7 10 9 8 5 10 7 11 8 12 8 9 11 8 9 14 15
	 [[Node: loss_2/dense_9_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _class=["loc:@train...s_grad/mul"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](loss_2/dense_9_loss/Log, loss_2/dense_9_loss/Cast)]]

In [ ]:
import matplotlib.pyplot as plt
def show_train_history(train_history,train,validation):
    plt.plot(train_history.history[train])
    plt.plot(train_history.history[validation])
    plt.title('Train History')
    plt.ylabel(train)
    plt.xlabel('Epoch')
    plt.legend(['train', 'validation'], loc='upper left')
    plt.show()

In [ ]:
show_train_history(train_history,'acc','val_acc')

In [ ]:
show_train_history(train_history,'loss','val_loss')

In [ ]:
scores = model.evaluate(x=test_Features, 
                        y=test_Label)

In [ ]:
scores[1]