In [25]:
import numpy
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cross_validation import train_test_split
numpy.random.seed(10)

In [26]:
all_df = pd.read_csv("titanic.csv")

In [27]:
cols=['survived','pclass' ,'sex', 'age',
       'fare',]
df=all_df[cols]
df.isnull().sum()
df=df.values

In [28]:
X = df[:,1:]
Y = df[:,0]
X[:5]

array([[  1.    ,   0.    ,  29.    , 211.3375],
       [  1.    ,   1.    ,   0.9167, 151.55  ],
       [  1.    ,   0.    ,   2.    , 151.55  ],
       [  1.    ,   1.    ,  30.    , 151.55  ],
       [  1.    ,   0.    ,  25.    , 151.55  ]])

In [29]:
Y[:5]

array([1., 1., 0., 0., 0.])

In [30]:
 X = StandardScaler().fit_transform(X)
train_Features, test_Features, train_Label, test_Label = train_test_split(X, Y, test_size=0.2, random_state=True) 
len(train_Features)

1046

In [31]:
train_Features[355:359]

array([[ 0.84246649, -1.34419751,  0.8216082 , -0.46039806],
       [ 0.84246649, -1.34419751,  0.09991351, -0.19415727],
       [ 0.84246649,  0.74393829, -0.18876436, -0.49092056],
       [-0.35140802, -1.34419751,  0.17208298, -0.23764487]])

In [32]:
train_Features[:4]

array([[-1.54528253, -1.34419751,  0.09991351,  1.02832767],
       [ 0.84246649,  0.74393829,  1.54330288, -0.48794021],
       [ 0.84246649,  0.74393829, -0.69395064, -0.49092056],
       [ 0.84246649,  0.74393829, -0.5496117 , -0.49373855]])

In [33]:
train_Label[:4]

array([1., 0., 0., 0.])

In [34]:
from keras.models import Sequential
from keras.layers import Dense,Dropout

In [35]:
model = Sequential()

In [36]:
model.add(Dense(units=40, input_dim=4, 
                kernel_initializer='uniform', 
                activation='relu',trainable=False))

In [37]:
model.add(Dense(units=1, 
                kernel_initializer='uniform',
                activation='sigmoid'))

In [38]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 40)                200       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 41        
Total params: 241
Trainable params: 41
Non-trainable params: 200
_________________________________________________________________


In [39]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

In [40]:
model.fit(x=train_Features,y=train_Label)

Epoch 1/1
1046/1046 [==============================] - 0s 276us/step - loss: 0.6901 - acc: 0.6558


In [41]:
model.layers[0].input

<tf.Tensor 'dense_4_input:0' shape=(?, 4) dtype=float32>

In [42]:
model.layers[0].output

<tf.Tensor 'dense_4/Relu:0' shape=(?, 40) dtype=float32>

In [43]:
model.layers[1].input

<tf.Tensor 'dense_4/Relu:0' shape=(?, 40) dtype=float32>

In [44]:
model.layers[1].output

<tf.Tensor 'dense_5/Sigmoid:0' shape=(?, 1) dtype=float32>

In [45]:
scores = model.evaluate(x=test_Features, 
                        y=test_Label)

262/262 [==============================] - 0s 549us/step


In [46]:
scores[1]

0.6870229012183561