In [73]:
from sklearn import metrics
from sklearn.ensemble import ExtraTreesClassifier
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
import csv
np.random.seed(10)
%matplotlib inline  

In [74]:
all_df = pd.read_excel("data/titanic3.xls")

In [75]:
all_df[:4]

pclass  survived                                  name     sex      age  \
0       1         1         Allen, Miss. Elisabeth Walton  female  29.0000   
1       1         1        Allison, Master. Hudson Trevor    male   0.9167   
2       1         0          Allison, Miss. Helen Loraine  female   2.0000   
3       1         0  Allison, Mr. Hudson Joshua Creighton    male  30.0000   

   sibsp  parch  ticket      fare    cabin embarked boat   body  \
0      0      0   24160  211.3375       B5        S    2    NaN   
1      1      2  113781  151.5500  C22 C26        S   11    NaN   
2      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3      1      2  113781  151.5500  C22 C26        S  NaN  135.0   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON

In [76]:
cols=['survived','name','pclass' ,'sex', 'age', 'sibsp',
      'parch', 'fare', 'embarked']
all_df=all_df[cols]
df=all_df.drop(['name'], axis=1)
df['sex']= df['sex'].map({'female':0, 'male': 1}).astype(int)
df = pd.get_dummies(data=df,columns=["embarked" ])
df.isnull().sum()

survived        0
pclass          0
sex             0
age           263
sibsp           0
parch           0
fare            1
embarked_C      0
embarked_Q      0
embarked_S      0
dtype: int64

In [77]:
df.count()

survived      1309
pclass        1309
sex           1309
age           1046
sibsp         1309
parch         1309
fare          1308
embarked_C    1309
embarked_Q    1309
embarked_S    1309
dtype: int64

In [78]:
df2=df.dropna(axis=0,how='any')
df2.count()
df2[:5]

survived  pclass  sex      age  sibsp  parch      fare  embarked_C  \
0         1       1    0  29.0000      0      0  211.3375         0.0   
1         1       1    1   0.9167      1      2  151.5500         0.0   
2         0       1    0   2.0000      1      2  151.5500         0.0   
3         0       1    1  30.0000      1      2  151.5500         0.0   
4         0       1    0  25.0000      1      2  151.5500         0.0   

   embarked_Q  embarked_S  
0         0.0         1.0  
1         0.0         1.0  
2         0.0         1.0  
3         0.0         1.0  
4         0.0         1.0

In [79]:
df3=df2.values

In [80]:
y=np.round(df3[:,3])
y

array([29.,  1.,  2., ..., 26., 27., 29.])

In [81]:
x=np.delete(df3,3, axis=1)
x[:2]

array([[  1.    ,   1.    ,   0.    ,   0.    ,   0.    , 211.3375,
          0.    ,   0.    ,   1.    ],
       [  1.    ,   1.    ,   1.    ,   1.    ,   2.    , 151.55  ,
          0.    ,   0.    ,   1.    ]])

In [82]:
df4 = df[df['age'].isnull()==True]
df5=df4.drop(['age'], axis=1)
df5

survived  pclass  sex  sibsp  parch      fare  embarked_C  embarked_Q  \
15           0       1    1      0      0   25.9250         0.0         0.0   
37           1       1    1      0      0   26.5500         0.0         0.0   
40           0       1    1      0      0   39.6000         1.0         0.0   
46           0       1    1      0      0   31.0000         0.0         0.0   
59           1       1    0      0      0   27.7208         1.0         0.0   
69           1       1    0      0      1   55.0000         0.0         0.0   
70           0       1    1      0      0    0.0000         0.0         0.0   
74           0       1    1      0      0   52.0000         0.0         0.0   
80           0       1    1      0      0   26.5500         0.0         0.0   
106          0       1    1      0      0  221.7792         0.0         0.0   
107          1       1    0      0      0   31.6833         0.0         0.0   
108          1       1    0      0      0  110.8833         1.0         0.0   
118          0       1    1      0      0   26.5500         0.0         0.0   
121          1       1    0      1      0  133.6500         0.0         0.0   
125          0       1    1      0      0    0.0000         0.0         0.0   
134          1       1    0      1      0   89.1042         1.0         0.0   
147          0       1    1      0      0   42.4000         0.0         0.0   
152          1       1    1      0      0   30.0000         0.0         0.0   
157          0       1    1      0      0   51.8625         0.0         0.0   
166          0       1    1      0      0   30.6958         1.0         0.0   
176          1       1    0      1      0   51.8625         0.0         0.0   
179          0       1    1      0      0   26.5500         0.0         0.0   
184          0       1    1      0      0   27.7208         1.0         0.0   
196          1       1    1      0      0   29.7000         1.0         0.0   
204          1       1    0      1      0   82.1708         1.0         0.0   
219          1       1    1      0      0   25.7417         1.0         0.0   
223          0       1    1      0      0    0.0000         0.0         0.0   
235          1       1    1      0      0   39.6000         0.0         0.0   
237          0       1    1      0      0  227.5250         1.0         0.0   
241          0       1    1      0      0   50.0000         0.0         0.0   
...        ...     ...  ...    ...    ...       ...         ...         ...   
1202         0       3    1      0      0    8.0500         0.0         0.0   
1212         0       3    1      0      0    7.8958         0.0         0.0   
1213         0       3    1      0      0    8.0500         0.0         0.0   
1214         0       3    1      0      0    8.6625         0.0         0.0   
1215         0       3    1      0      0    7.7500         0.0         1.0   
1216         1       3    0      0      0    7.7333         0.0         1.0   
1219         0       3    1      0      0    8.0500         0.0         0.0   
1221         0       3    1      0      0    7.8958         0.0         0.0   
1241         0       3    1      1      0    6.4375         1.0         0.0   
1242         0       3    1      0      0    6.4375         1.0         0.0   
1243         0       3    1      0      0    7.2250         1.0         0.0   
1245         0       3    1      0      0    8.0500         0.0         0.0   
1246         0       3    1      1      0   16.1000         0.0         0.0   
1247         1       3    0      1      0   16.1000         0.0         0.0   
1249         0       3    1      0      0    7.7500         0.0         1.0   
1250         0       3    1      0      0    7.8958         0.0         0.0   
1253         0       3    1      0      0    7.2292         1.0         0.0   
1255         0       3    1      0      0    7.2292         1.0         0.0   
1262         0       3    1      1      1   14.5000     

In [83]:
knn= KNeighborsClassifier(n_neighbors=10)
trained_model =knn.fit(x,y)

In [84]:
imputed_values = trained_model.predict(df5)
len(imputed_values)
imputed_values

array([30., 36.,  1., 25., 53., 25., 49., 31., 42., 18., 19., 17., 42.,
        6., 49., 33.,  1., 19., 31., 26., 35., 42., 28., 26., 23., 35.,
       49.,  1., 18., 31., 19., 36., 30., 58., 28., 35., 46., 28.,  8.,
       49., 31., 49., 49., 28., 49., 16., 61., 27., 40., 27., 49., 27.,
       49., 36., 42., 22., 30.,  9., 30., 27., 18., 28., 24., 26., 26.,
       22., 30., 30., 24., 18., 21., 21., 21., 32., 22., 21., 22., 47.,
       18., 16., 22., 34., 34., 28., 21., 16., 32., 18., 21., 18., 21.,
       26., 26., 25., 16., 32.,  4.,  4.,  4.,  4., 22., 21., 22., 16.,
       16., 21., 27., 18., 21., 21., 21., 18., 30., 26., 32., 32., 21.,
        3., 24., 24., 24.,  7.,  9., 30., 31., 18., 26., 26., 18., 16.,
       18., 21., 22., 22., 16., 22., 22., 18., 16., 21., 30., 30.,  2.,
       16., 28., 16., 21., 18., 28., 28., 21., 22., 26., 16., 22., 30.,
       28., 21., 21., 21.,  9.,  9.,  9., 22., 22., 16., 22., 19., 19.,
       40., 26., 22., 18., 26., 30., 31., 19., 21., 21., 21., 18

In [85]:
df5.insert(loc=3, column='age', value=imputed_values)

In [86]:
df5[:5]

survived  pclass  sex   age  sibsp  parch     fare  embarked_C  \
15         0       1    1  30.0      0      0  25.9250         0.0   
37         1       1    1  36.0      0      0  26.5500         0.0   
40         0       1    1   1.0      0      0  39.6000         1.0   
46         0       1    1  25.0      0      0  31.0000         0.0   
59         1       1    0  53.0      0      0  27.7208         1.0   

    embarked_Q  embarked_S  
15         0.0         1.0  
37         0.0         1.0  
40         0.0         0.0  
46         0.0         1.0  
59         0.0         0.0

In [93]:
dff = pd.concat([df2,df5],axis=0)
dff
dff[dff['fare']==0]

survived  pclass  sex   age  sibsp  parch  fare  embarked_C  embarked_Q  \
7            0       1    1  39.0      0      0   0.0         0.0         0.0   
150          0       1    1  40.0      0      0   0.0         0.0         0.0   
170          1       1    1  49.0      0      0   0.0         0.0         0.0   
234          0       1    1  38.0      0      0   0.0         0.0         0.0   
896          0       3    1  49.0      0      0   0.0         0.0         0.0   
898          0       3    1  19.0      0      0   0.0         0.0         0.0   
963          0       3    1  36.0      0      0   0.0         0.0         0.0   
1254         1       3    1  25.0      0      0   0.0         0.0         0.0   
70           0       1    1  49.0      0      0   0.0         0.0         0.0   
125          0       1    1  49.0      0      0   0.0         0.0         0.0   
223          0       1    1  49.0      0      0   0.0         0.0         0.0   
363          0       2    1  49.0      0      0   0.0         0.0         0.0   
384          0       2    1  49.0      0      0   0.0         0.0         0.0   
410          0       2    1  49.0      0      0   0.0         0.0         0.0   
473          0       2    1  49.0      0      0   0.0         0.0         0.0   
528          0       2    1  49.0      0      0   0.0         0.0         0.0   
581          0       2    1  49.0      0      0   0.0         0.0         0.0   

      embarked_S  
7            1.0  
150          1.0  
170          1.0  
234          1.0  
896          1.0  
898          1.0  
963          1.0  
1254         1.0  
70           1.0  
125          1.0  
223          1.0  
363          1.0  
384          1.0  
410          1.0  
473          1.0  
528          1.0  
581          1.0

In [92]:
dff.to_csv('titanic.csv')